"""v1.0.0 | 2026-09-07 | 自检独立配套文件和教学练习。"""
from pathlib import Path
from decimal import Decimal
import subprocess,tempfile,shutil,json,sys,tomllib
R=Path(__file__).resolve().parent;kit=R;qa=R/'本地自检输出';qa.mkdir(exist_ok=True)
results={}
for name,args in [('配置静态检查',['检查配置_v1.0.0.py','--self-test']),('Responses本地模拟',['验证Responses_v1.0.0.py'])]:
    p=subprocess.run([sys.executable,'-X','utf8',*args],cwd=kit,text=True,capture_output=True,encoding='utf-8');assert p.returncode==0,p.stderr
    results[name]=json.loads(p.stdout)
with tempfile.TemporaryDirectory(prefix='caige-desktop-exercise-') as tmp:
    d=Path(tmp)
    for name in ['orders.py','test_orders.py']:shutil.copyfile(kit/'桌面练习'/name,d/name)
    p=subprocess.run([sys.executable,'-X','utf8','-m','unittest','-v'],cwd=d,text=True,capture_output=True,encoding='utf-8')
    assert p.returncode!=0 and 'failures=3' in p.stderr,p.stderr
    results['练习初始状态']='3 tests fail, deliberately'
    shutil.copyfile(kit/'参考答案/orders.py',d/'orders.py')
    p=subprocess.run([sys.executable,'-X','utf8','-m','unittest','-v'],cwd=d,text=True,capture_output=True,encoding='utf-8')
    assert p.returncode==0,p.stderr
    results['人工参考答案']='3 tests pass; not generated by DeepSeek'
data=json.loads((kit/'价格情景_v1.0.0.json').read_text(encoding='utf-8'));totals={}
for m in data['models']:
    peak=Decimal(str(m['peakInputMiss']))+Decimal('0.1')*Decimal(str(m['peakOutput']))
    totals[m['model']]={'peak':str(peak),'offPeak':str(peak*Decimal('.5'))}
assert totals['deepseek-v4-flash']['peak']=='3.9' and totals['deepseek-v4-pro']['peak']=='11.7'
results['费用独立复算']=totals
tomllib.loads((kit/'配置结构示例_v1.0.0.toml').read_text(encoding='utf-8'))
results['线上DeepSeek联调']='not performed; no real API key supplied'
(qa/'配套自检结果_v1.0.0.json').write_text(json.dumps(results,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps(results,ensure_ascii=False,indent=2))
